.TH "pnGF::BasicWin" 3 "Sat Feb 2 2019" "Version 1.0.0" "花生游戏框架" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pnGF::BasicWin \- 这是一个基础的Windows SDK封装类\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BasicWin\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBGetState\fP ()"
.br
.ti -1c
.RI "HWND \fBRunWindow\fP (string jsonPath)"
.br
.ti -1c
.RI "float \fBGetFPS\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBBasicWin\fP & \fBInstance\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBmouseClick\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
这是一个基础的Windows SDK封装类\&. 

TODO: 它包含了注册窗口到运行窗体程序的一系列步骤
.PP
\fBNote:\fP
.RS 4
.RE
.PP
\fBAuthor:\fP
.RS 4
CodeLoser
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0
.RE
.PP
\fBDate:\fP
.RS 4
2/1 2019
.RE
.PP
Contact: pokkemon@outlook.com 

.SH "Author"
.PP 
Generated automatically by Doxygen for 花生游戏框架 from the source code\&.
